name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:
  test-or-release:
    runs-on: macos-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - name: Build
      run: npm run produce
    - name: Test
      run: npm test
    - name: Publish
      uses: prantlf/publish-release-action@v1
      with:
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
